use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'lottie-swift_macOS' do
  platform :osx, '10.13'
  pod 'lottie-ios', :path => '../'
end

target 'lottie-swift_Example' do
  platform :ios, '11.0'
  pod 'ZippyJSON', :git => 'https://github.com/michaeleisel/zippyjson', :branch => 'master'
  pod 'lottie-ios', :path => '../'

  target 'lottie-swift_Tests' do
    inherit! :search_paths
  end
end